### ISSUE TITLE
code run error

### ISSUE THREAD

**Issue by 4575759ww** [deependersingla/deep_trader#11]
when I run python dqn_model.py in tensor-reinforcement,i got an error(I have mkdir saved_networks,and get data.pk land data_dict.pkl in tensor-reinforcement):
Traceback (most recent call last):
  File "/Users/nicefilm/Documents/code/python/deep-trader/tensor-reinforcement/dqn_model.py", line 11, in <module>
    from train_stock import *
  File "/Users/nicefilm/Documents/code/python/deep-trader/tensor-reinforcement/train_stock.py", line 23, in <module>
    supervised_y_data  = episodic_data.make_supervised_data(data, data_dict)
  File "/Users/nicefilm/Documents/code/python/deep-trader/tensor-reinforcement/episodic_data.py", line 100, in make_supervised_data
    supervised_data.append(episode_supervised_data(episode, data_dict))
  File "/Users/nicefilm/Documents/code/python/deep-trader/tensor-reinforcement/episodic_data.py", line 87, in episode_supervised_data
    prices.append(data_average_price(data_dict, iteration))
  File "/Users/nicefilm/Documents/code/python/deep-trader/tensor-reinforcement/episodic_data.py", line 92, in data_average_price
    data = data_dict[list_md5_string_value(data)]
KeyError: '297956b2300474fda50a2a6b1d41a714'

**Comment by soloman817** [comment]
I have the same problem

**Comment by tubu** [comment]
I have the same problem

**Comment by deependersingla** [comment]
@tubu @soloman817  @4575759ww  Copy data from https://drive.google.com/file/d/0B6ZrYxEMNGR-MEd5Ti0tTEJjMTQ/view and https://drive.google.com/file/d/0B6ZrYxEMNGR-Q0YwWWVpVnJ3YmM/view?usp=sharing into tensor-reinforcement directory.

**Comment by tubu** [comment]
@deependersingla I download the two files and copy data to tensor-reinforcement directory,but have the same problem.

**Comment by codnoob** [comment]
@deependersingla, I also have the two .pkl files in the directory yet the error shows. 
@tubu, @soloman817, @4575759ww were you able to work through it?

**Comment by xiaoxiaojiangshang** [comment]
I have the same problems，were you able to work through it？ @deependersingla

**Comment by david200340105** [comment]
I also have the problem, although i download the two .pkl file and copy to the directory.
