### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by yeshengyi** [deependersingla/deep_trader#19]
when I run it, I encounter the following error:

Warning (from warnings module):
  File "C:\Users\ben\AppData\Local\Programs\Python\Python36\lib\site-packages\sklearn\cross_validation.py", line 41
    "This module will be removed in 0.20.", DeprecationWarning)
DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
Traceback (most recent call last):
  File "C:\Users\ben\Documents\python\deep_trader\tensor-reinforcement\dqn_model.py", line 11, in <module>
    from train_stock import *
  File "C:\Users\ben\Documents\python\deep_trader\tensor-reinforcement\train_stock.py", line 22, in <module>
    data = episodic_data.load_data("data.pkl",episode=10)
  File "C:\Users\ben\Documents\python\deep_trader\tensor-reinforcement\episodic_data.py", line 77, in load_data
    data = load_file_data(file)
  File "C:\Users\ben\Documents\python\deep_trader\tensor-reinforcement\episodic_data.py", line 82, in load_file_data
    data = six.moves.cPickle.load(myFile)
UnicodeDecodeError: 'ascii' codec can't decode byte 0x97 in position 0: ordinal not in range(128)
>>> 

Can someone help me out here?

**Comment by tivvit** [comment]
looks like python2 vs python3 problem

**Comment by yeshengyi** [comment]
I use python3

**Comment by smileyung** [comment]
**UnicodeDecodeError: 'ascii' codec can't decode byte 0x97 in position 0: ordinal not in range(128)**
I have the same problem with python 3

/home/smilewater/anaconda3/envs/tensorflow-gpu/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
Traceback (most recent call last):
  File "dqn_model.py", line 11, in <module>
    from train_stock import *
  File "/media/smilewater/Disk/pywork/SinicaFinancial/deep_trader/tensor-reinforcement/train_stock.py", line 21, in <module>
    data = episodic_data.load_data("data.pkl",episode=10)
  File "/media/smilewater/Disk/pywork/SinicaFinancial/deep_trader/tensor-reinforcement/episodic_data.py", line 71, in load_data
    data = load_file_data(file)
  File "/media/smilewater/Disk/pywork/SinicaFinancial/deep_trader/tensor-reinforcement/episodic_data.py", line 76, in load_file_data
    data = six.moves.cPickle.load(myFile)
UnicodeDecodeError: 'ascii' codec can't decode byte 0x97 in position 0: ordinal not in range(128)

**Comment by BTCTON** [comment]
def load_file_data(file):
    with open(file, 'rb') as myFile:
        # data = six.moves.cPickle.load(myFile)
        data = pickle.load(myFile, encoding='latin')
    return data

change episodic_data.py to this.

**Comment by jojojo9594165** [comment]
I have tried the solution you provided but i got an other error.

return hashlib.md5(string).hexdigest()
Unicode-objects must be encoded before hashing

how do you think I can fix this?

**Comment by stevexxs** [comment]
just change
data = six.moves.cPickle.load(myFile)
to 
data = six.moves.cPickle.load(myFile, encoding='bytes')
