### ISSUE TITLE
code run problem

### ISSUE THREAD

**Issue by HubFire** [deependersingla/deep_trader#6]
when I run `python python dqn_model.py` in tensor-reinforcement,i got  an error(I have  mkdir saved_networks,and get data.pk land data_dict.pkl in tensor-reinforcement):
`Traceback (most recent call last):
  File "dqn_model.py", line 11, in <module>
    from train_stock import *
  File "/home/deep_trader/tensor-reinforcement/train_stock.py", line 23, in <module>
    supervised_y_data  = episodic_data.make_supervised_data(data, data_dict)
  File "/home/deep_trader/tensor-reinforcement/episodic_data.py", line 99, in make_supervised_data
    supervised_data.append(episode_supervised_data(episode, data_dict))
  File "/home/deep_trader/tensor-reinforcement/episodic_data.py", line 86, in episode_supervised_data
    prices.append(data_average_price(data_dict, iteration))
  File "/home/deep_trader/tensor-reinforcement/episodic_data.py", line 91, in data_average_price
    data =  data_dict[list_md5_string_value(data)]
KeyError: '297956b2300474fda50a2a6b1d41a714'
`

**Comment by 4575759ww** [comment]
Hi，I meet the same problem, how did you solve it ? Hope you can tell me, thank you!

**Comment by codnoob** [comment]
I have this same error too! Pelase let me know how were you able to close this issue.
